Vitaly/bos 13 14 16
GameDev-Academy/Boss-Slasher pull request #18
Opened 2022-06-04 16:10 UTC by Vitaly086

Doors open mechanics; 
Rooms and Levels pass mechanics;
Add dungeon controller

https://user-images.githubusercontent.com/93872632/172015152-249bc860-caea-4b28-82fd-472330284aaa.mp4

.

2022-06-04 16:28 UTC, ViktoriaBanda requested changes

2022-06-04 16:28 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/Door.cs
> +    }
Метод с названием IsOpen по идее должен возвращать тип bool. Думаю, надо поменять название метода.

2022-06-04 16:28 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/Level.cs
> +        public bool LevelPassed { get; private set; }
Переменная типа bool - лучше назвать IsLevelPassed

2022-06-04 17:14 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/Room.cs
> +            {
Мне кажется, довольно затратно такие вещи делать в Апдейте, особенно, если врагов будет очень много.

2022-06-04 17:18 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/Level.cs
> +            {
С комнатами и уровнями тоже, в апдейте ходить по всему массиву и проверять - не очень производительно. Может, как вариант, создать переменную с количеством всех комнат и переменную с количеством пройденных комнат ( ей делать ++ при прохождении комнаты). А в апдейте просто сравнивать обе переменные.

2022-06-15 16:30 UTC, ViktoriaBanda requested changes

2022-06-15 16:30 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/CloseDoorTrigger.cs
> +                .AddTo(this);
Дверь должна закрыться, когда в нее заходит игрок? а если в нее зайдет кто-то другой первым (враг например подвижный), то игрок уже туда не попадет?

2022-06-15 16:30 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/DungeonManager.cs
> +                    .Where(_ => _)
зачем тут Where, если в нем ничего нет?

2022-06-15 16:30 UTC, ViktoriaBanda commented on Assets/Scripts/Battle/DungeonManager.cs
> +                .Where(_ => _)
и тут тоже зачем Where?

2022-06-17 16:36 UTC, PapkovNikita requested changes

2022-06-17 16:36 UTC, PapkovNikita commented on Assets/Scripts/Battle/DungeonManager.cs
> +                    .Subscribe(_ => OpenNextLevel())
учти только что могут быть замыкания

2022-06-17 16:36 UTC, PapkovNikita commented on Assets/Scripts/Battle/DungeonManager.cs
> +                    .Subscribe(_ => OpenNextLevel())
но райдер тебя предупредит

2022-06-17 16:36 UTC, PapkovNikita commented on Assets/Scripts/Battle/Room.cs
> +                .Select(value => value.All(_ => _))
код таким образом становится не читабельным.

isDeadProperties => isDeadProperties.All(isDead => isDead == true)

2022-06-19 12:17 UTC, npapkov approved these changes

2022-06-19 12:18 UTC, merged